AllCops:
  TargetRubyVersion: 2.4
  Include:
    - "Gemfile"
    - "Rakefile"
  Exclude:
    - "source/trips/**/*"
    - "source/images/**/*"
  DisplayCopNames: true
  UseCache: true
  CacheRootDirectory: ./tmp

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  # Max: 100
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
